version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: python_learn
      POSTGRES_USER: python_learn
      POSTGRES_PASSWORD: python_learn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: python_learn

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: art_krishtop@mail.ru
      PGADMIN_DEFAULT_PASSWORD: qwerty123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  default:
    name: python_learn
