version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: python_learn
      POSTGRES_USER: python_learn
      POSTGRES_PASSWORD: python_learn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres_container

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: art_krishtop@mail.ru
      PGADMIN_DEFAULT_PASSWORD: qwerty123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    container_name: pgadmin_container

  tasks:
    build: ./python
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres+psycorg2://python_learn:python_learn@postgres:5432/python_learn
    volumes:
      - ./tasks/№1_2:/app/№1_2
      - ./tasks/№2_2:/app/№2_2
    container_name: tasks_container

  fastapi:
    build: ./fastapi
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres+psycorg2://python_learn:python_learn@postgres:5432/python_learn
    volumes:
      - ./tasks/№3_1:/app
    ports:
      - "8000:8000"
    container_name: fastapi_container

volumes:
  postgres_data:

networks:
  default:
    name: python_learn
